### ISSUE TITLE
Ho and Ha (solution) should be different for exercise 1

### ISSUE THREAD

**Issue by vishalpatel2890** [learn-co-curriculum/dsc-0-07-19-1-sample-z-test#1]
solution says: 
# Ha : time to rent the car is greater than 60 seconds
# Ho : time to rent a car is less than or equal to 60 sec

wording of the problem needs to be reworked or correct ho and ha are: 
# Ha : time to rent the car is not 60 seconds
# Ho : time to rent a car is 60 sec

**Comment by ShakeelRaja** [comment]
fixed the problem statement to reflect stated  Ho and Ha ..
"A rental car company claims the mean time to rent a car on their website is 60 seconds or less, with a standard deviation of 30 seconds."
